name: spatial-docs
channels:
  - conda-forge
dependencies:
  - cython
  - docutils<0.18
  - fontconfig
  - freetype
  - graphviz
  - matplotlib
  - notebook
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - sphinx-argparse>=0.4
    - ..
